name: QuestAdder
version: '${version}'
main: kor.toxicity.questadder.QuestAdderBukkit
author: toxicity
description: Make a various quest in your server!
load: POSTWORLD
api-version: 1.17
depend:
  - Citizens
  - ProtocolLib
softdepend:
  - Vault
  - ItemsAdder
  - Oraxen
  - PlaceholderAPI
  - WorldGuard
  - MagicSpells
  - MythicMobs
  - MultiWorld
  - SuperiorSkyblock2
  - MythicLib
  - MMOCore
  - MMOItems
  - LightAPI
commands:
  questadder:
    aliases:
      - qa
    description: QuestAdder's command.
    usage: /<command>
  quest:
    aliases:
      - q
      - 퀘스트
      - 퀘
    description: QuestAdder's quest command.
    usage: /<command>